MappingRules:
  Prefix:
    Plotter: "plot"
    Model: "model"
    Scenario: "scen"
  Components:
    Plotter:
      inputVar:
        - source: { Model: "outputVar" }
          destination: { Plotter: "inputVar" }
          type: postStepMappings
        - source: { Scenario: "outputVar" }
          destination: { Plotter: "inputVar" }
          type: preStepMappings
    Scenario:
      outputVar:
        - destination: { Model: "inputVar" }
          type: preStepMappings