Logger:
  type: logger
  path: example/results/
  usetex: false #optional, true for use of Latex renderer
  fontfamily: sans-serif #optional, serif for latex style font
  inputVar:
    log.in.y:
      init: 0
      nodeID: y
    log.in.u:
      init: 0
      nodeID: u
  plots:
    scatter_example:
      type: scatter
      title: Scatter Example
      subgrid: true #optional
      grid: true #optional
      vars:
        - log.in.u
      x_var: log.in.y
      legend: #optional
        - u over y
      xlabel: Y with some \LaTeX
      ylabel: U
