Logger:
  type: logger
  path: example/results/
  usetex: false #optional, true for use of Latex renderer
  fontfamily: sans-serif #optional, serif for latex style font
  inputVar:
    log.in.y:
      init: 0
      nodeID: y
    log.in.u:
      init: 0
      nodeID: u
  plots:
    step_response:
      type: time_series
      title: Filter Step Response
      subgrid: true #optional
      grid: true #optional
      vars:
        - log.in.u
        - log.in.y
      legend: #optional
        - u
        - y
      xlabel: Time [s]
      ylabel: Signal Value
