Plotter:
  type: plotter
  outputFolder: example/results/
  usetex: false #optional, true for use of Latex renderer
  fontfamily: sans-serif #optional, serif for latex style font
  inputVar:
    plot.in.y:
      init: 0
      nodeID: y
    plot.in.u:
      init: 0
      nodeID: u
  plots:
    scatter_example:
      type: scatter
      title: Scatter Example
      subgrid: true #optional
      grid: true #optional
      vars:
        - u
      x_var: y
      legend: #optional
        - u over y
      xlabel: Y with some \LaTeX
      ylabel: U
