modular_config: True # Set to True if the config is a modular config. If set to False or not present the config is treated as a full config.

# Components: This section defines the structure and loading order of component configurations.
# Keys: Represent subdirectories within the config_directory.
# Values: Can be either a string (single file) or a list (multiple files) containing component settings.
# File naming: Single file - value is filename without .yaml extension; Multiple files - list filenames without extensions in desired loading order.
# Example: model: Filter loads 'Filter.yaml' from 'config_directory/model/' subdirectory.
# Example: plotter: [scatter_example, step_response] loads files in that order from 'config_directory/plotter/'.
# Note: The loading order of components can be crucial for managing component dependencies.

General:
  outputFolder: example/results/
  # customComponents:
  #   CustomComponentClass:
  #     pathToComponent: path.to.custom.component

Components:
  model: Filter
  connection: FMU
  plotter:
    - scatter_example
    - step_response
  scenario:
    - scenario1
    - customScenario
  mapping: mapping

# END_COMPONENT_DEFINITIONS

Master:
  type: standalone-master
  timeStepPerCycle: 0.01
  # tend: 4

Model:
  stepSize: 0.01

Plotter:
  outputFolder: {{ General.outputFolder }}
  mergePlot: true

Scenario:
  outputFolder: {{ General.outputFolder }}
